---
- name: Include OS-specific variables
  tags: dnscrypt-proxy
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      skip: true

- import_tasks: install.yml
  tags: dnscrypt-proxy

- import_tasks: configure.yml
  tags: dnscrypt-proxy
