---
- name: restart dnscrypt-proxy
  service:
    name: "{{ dnscrypt_proxy_service_name }}"
    state: restarted
  when: dnscrypt_proxy_service_enabled or
        dnscrypt_proxy_service_state in ["started", "restarted", "reloaded"]
