---
- name: restart dnscrypt-proxy
  systemd:
    name: "{{ __dnscrypt_proxy_service_name }}"
    state: restarted
  when: dnscrypt_proxy_service_enabled or
        dnscrypt_proxy_service_state != 'stopped'

- name: restart networkmanager
  systemd:
    name: NetworkManager
    state: restarted
